export const SELECTORS = {
  menuHamburguesa: '[data-tour="menu-hamburguesa"]',
  menuCerrar: '[data-tour="menu-cerrar"]',
  navMaestro: '[data-tour="nav-maestro"]',
  navRecetas: '[data-tour="nav-recetas"]',
  maestroTipo: '[aria-label="Navegar a Tipo de Ingrediente"]',
  maestroIngrediente: '[aria-label="Navegar a Ingredientes y/o Utensilios"]',
  tipoNuevo: '[data-tour="tipo-ingrediente-nuevo"]',
  tipoVolver: '[data-tour="tipo-ingrediente-volver"]',
  ingredienteNuevo: '[data-tour="ingrediente-nuevo"]',
  recetaNueva: '[data-tour="receta-nueva"]',
  recetaWizard: '[data-tour="receta-wizard"]',
  recetaInfoBase: '[data-tour="receta-info-base"], [data-tour="receta-wizard"]',
  recetaNombre: '[data-tour="receta-nombre"]',
  recetaFamiliaMenu: '[data-tour="receta-familia-menu"]',
  recetaAreaPreparacion: '[data-tour="receta-area-preparacion"]',
  recetaSiguiente: '[data-tour="receta-siguiente"]',
  recetaGuardar: '[data-tour="receta-guardar"]',
  recetaIngredientes: '[data-tour="receta-ingredientes-area"]',
  recetaIngredientesLista: '[data-tour="receta-ingredientes-lista"]',
  recetaPreparacion: '[data-tour="receta-preparacion-area"]',
  recetaPreparacionLista: '[data-tour="receta-preparacion-lista"]',
  modalFormulario: '[data-tour="entity-modal"]',
} as const;
